
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doihwejzczzfvxaonrkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvaWh3ZWp6Y3p6ZnZ4YW9ucmt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTI1MjMsImV4cCI6MjA1OTUyODUyM30.ztwt5PYZfXMe2tj6ZJm9yUed8rQLs1QVA8WkJVff5m0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
